---
title: "Cleaning_Data"
author: "Alicia Dagle"
date: "November 7, 2019"
output: github_document
---


```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```


```{r}
#Maternal Mortality ratio from gapminder dataset
maternal_mort = read_csv("./data/Gapminder/maternal_mortality_ratio_per_100000_live_births.csv") %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    x1800:x2013,
    names_to = "year",
    values_to = "maternal_mortality"
  ) %>% 
  mutate(year = str_remove(year,"x"))

view(maternal_mort)


```



```{r}
#births attended by skilled health staff (percent of total)
staff = read_csv("./data/Gapminder/births_attended_by_skilled_health_staff_percent_of_total.csv")  %>% 
  janitor::clean_names() %>% 
  pivot_longer(
    x1984:x2017,
    names_to = "year",
    values_to = "perc_births_attended"
  ) %>% 
  mutate(year = str_remove(year,"x"))
  






```

```{r explore_matmort_birthsattended}
#This code is incomplete, I was just exploring a bit:
  
mortality_births_attend = inner_join(maternal_mort, staff, by = c("country","year")) 

  
 view(mortality_births_attend) 
  

  
#This is the process I would follow for merging the datasets for gdp sepnding, healthcare spending, and individual cost  (except this is done for the births attended here)
  
  maternal_mort_leading = maternal_mort %>%
  filter(year=='2013') %>% 
  filter(country %in% c("United States", "United Kingdom", "Finland", "Canada","Germany", "New Zealand", "Norway", "China", "Netherlands", "Switzerland", "Singapore", "Japan", "Luxembourg", "Hong Kong", "Qatar"))
  
view(maternal_mort_leading)


leading_2013 = left_join(maternal_mort_leading,staff, by = c("country","year"))

view(leading_2013)

```


