---
title: "healthcare_spending_data_cleaning"
author: "Michael Yan"
date: "11/16/2019"
output: github_document
editor_options: 
  chunk_output_type: console
---
# Healthcare spending (%GDP) vs. Country

```{r setup, include = FALSE}
library(tidyverse)
library(rvest)
library(plotly)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

## Import and clean data
```{r}
# Percent GDP that comes from health spending
health_spending_percent_gdp = read_csv("./data/WorldBank/health_spending_percent_GDP.csv") %>%
  janitor::clean_names() %>% 
  select(country_name, country_code, x2000:x2015) %>% 
  pivot_longer(
  x2000:x2015,
  names_to = "year",
  values_to = "health_spending_percent_GDP") %>% 
  rename("health_spending_percent_gdp" = "health_spending_percent_GDP") %>% 
  mutate(year = str_remove(year,"x")) %>% 
  mutate(health_spending_percent_gdp = round(health_spending_percent_gdp, digits = 2)) %>% 
  mutate(country_name = as.factor(country_name),
         country_code = as.factor(country_code),
         year = as.numeric(year)) %>% 
  rename(country = country_name,
         code = country_code)
```

## Filtered dataset to only include 10 countries in 2015
```{r}
healthcare_spending_2015_developed = 
  health_spending_percent_gdp %>% 
  filter(year == 2015) %>% 
  filter(country %in% c("United States", "United Kingdom", "Finland", 
                           "Canada","Germany", "New Zealand", "Norway", "Netherlands",
                           "Switzerland", "Japan"))
```

## Bar chart (% GDP that comes from healthcare spending in 10 developed countries)
```{r}
ten_developed_countries_health_spending = 
  healthcare_spending_2015_developed %>% 
  mutate(country = as.factor(country),
    country = fct_reorder(country, health_spending_percent_gdp)) %>% 
  ggplot(aes(x = country, y = health_spending_percent_gdp, fill = country)) +
  geom_col(position = "dodge") +
  coord_flip() +
  labs(x = "Developed countries",
       y = "% GDP that comes from healthcare spending",
       title = "Different amount of healthcare spending across 10 developed countries")

ggplotly(ten_developed_countries_health_spending)
```
