---
title: "Proposal"
author: "Duzhi Zhao"
date: "11/1/2019"
output: github_document
---
**Group members:**  
Duzhi Zhao (dz2426)  
Alicia Dagle (abd2150)  
Mengjia Lyu (ml4420)  
Michael Yan (qy2234)  
Clement Mugenzi (cm3928)

**Tentative project title:** 
Factors influencing Maternal Mortality Globally

**Motivation:** 
There is a global disparity between our current medical knowledge and our ability to influence positive maternal outcomes during birth. This burden is felt most heavily among developing countries such as Africa where maternal mortality rates are especially high. Even within more developed countries, there are surprising disparities. The United States has one of the highest maternal mortality rates out of developed countries despite high levels of spending on healthcare, which is not well understood. 

**Intended final products:**
A website containing interactive plots and general scope of the global maternal mortality issue. The project proposes to better understand how factors such as access to skilled health staff, socioeconomic status, and prenatal care influence maternal health birth outcomes.

**Anticipated data sources:**
[World Health Organization](http://apps.who.int/gho/data/node.main.530?lang=en)
[Our World in Data](https://ourworldindata.org/maternal-mortality)
[Center for Disease Control (CDC)](https://www.cdc.gov/nchs/products/databriefs/db328.htm)
[National Center for Health 
Statistics](https://www.cdc.gov/nchs/data/nvsr/nvsr67/nvsr67_05.pdf)
[UNICEF](https://data.unicef.org/resources/dataset/maternal-health-data/)

**Planned analyses/Visualizations/Coding challenges:**  
Using interactive maps (potentially using leaflet) to showcase the distribution of maternal health across countries.  
Using Bar plots or histograms to show maternal health trend over time.


**Planned timeline:**  
Clean data/Exploratory data analysis ~ 1 week  
Formal analysis/visualization ~2 weeks  
Interactive web tools/Screencast ~ 1 weeks


