---
title: "Shiny Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(highcharter)
library(flexdashboard)
library(tidyverse)
library(viridis)

library(plotly)

thm <- 
  hc_theme(
    colors = c("#1a6ecc", "#434348", "#90ed7d"),
    chart = list(
      backgroundColor = "transparent",
      style = list(fontFamily = "Source Sans Pro")
    ),
    xAxis = list(
      gridLineWidth = 1
    )
  )
cdc_maternal_death_data = read.delim("data/Underlying_Cause_of_Death_1999-2017.txt") %>%
  janitor::clean_names() %>%
  na.omit() %>%
  select(-notes, -gender_code, -hispanic_origin_code,-race_code,-state_code, -gender, -ten_year_age_groups_code) %>%
  group_by(state) %>%
  summarise(total_death = sum(deaths))

cdc_birth_data = read.csv("data/us_states_data.csv") %>%
  janitor::clean_names() %>%
  na.omit() %>%
  select(-total_population) %>%
  rename("state" = "state_of_residence") 
 
cdc_birth_data = cdc_birth_data[-52, ]
```

Column {data-width=600}
-----------------------------------------------------------------------

### Mortality Rates by State

```{r}
data("usgeojson")

cdc_merged_data = merge(x = cdc_maternal_death_data, 
                        y = cdc_birth_data,
                        by = "state",
                        all = TRUE) %>%
                  na.omit() %>%
                  mutate(mortality_rate = total_death/births)

n <- 4
colstops <- data.frame(
  q = 0:n/n,
  c = substring(viridis(n + 1), 0, 7)) %>%
  list_parse2()

highchart() %>%
  hc_add_series_map(usgeojson, cdc_merged_data, name = "Percent of Deaths",
                    value = "mortality_rate", joinBy =  c("woename", "state"),
                    dataLabels = list(enabled = TRUE,
                                      format = '{point.properties.postalcode}')) %>%
  hc_colorAxis(stops = colstops) %>%
  hc_legend(valueDecimals = 0, valueSuffix = "%") %>%
  hc_mapNavigation(enabled = TRUE) %>%
  hc_add_theme(thm)
```
Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}




```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

renderPrint({ 
  input[["boro_choice"]]
})

```

### Chart C

```{r}

```

